### ISSUE TITLE
`@EntityFormat` parameters on superclasses are being ignored if annotation without values is added to a child class

### ISSUE THREAD

**Issue by sclaresmt** [DISID/springlets#44]
When an entity with `@EntityFormat` extends from other entity which has the annotation too, Springlets its overriding the superclass `@EntityFormat` and using the information from the annotation on the subclass.

**Comment by cordin** [comment]
We are using the Spring's _AnnotatedElementUtils_ class _findMergedAnnotation_ method. It has the following javadoc comment:

_Find the first annotation of the specified annotationType within the annotation hierarchy above the supplied element, merge that annotation's attributes with matching attributes from annotations in lower levels of the annotation hierarchy, and synthesize the result back into an annotation of the specified annotationType._

The problem happens when you add the @EntityFormat annotation with any parameters in a parent class. If you don't add the annotation in a child class, it works as expected and takes the parent configuration. But if in a child class you add the annotation without any values, it seems the values are taken as empty and then the parent configuration is overwritten.

I think it would be better if an empty annotation takes, by default, the parent's configuration.

**Comment by cordin** [comment]
I'm unable to find a way to tell the AnnotatedElementUtils not to override attribute values in a parent class with default attribute values in a child class for the same annotation. Maybe the only option is to create a specific annotation utilities for this use case, or create a different annotation for child classes.
I don't think it's worth the effort, so if the @EntityFormat annotation is used in a child class, all the attribute values must be set, ignoring the parent class ones.
